// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package local

import (
	"context"

	"github.com/MetalBlockchain/metal-network-runner/network/node/status"
	mock "github.com/stretchr/testify/mock"
)

// NewNodeProcess creates a new instance of NodeProcess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNodeProcess(t interface {
	mock.TestingT
	Cleanup(func())
}) *NodeProcess {
	mock := &NodeProcess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NodeProcess is an autogenerated mock type for the NodeProcess type
type NodeProcess struct {
	mock.Mock
}

type NodeProcess_Expecter struct {
	mock *mock.Mock
}

func (_m *NodeProcess) EXPECT() *NodeProcess_Expecter {
	return &NodeProcess_Expecter{mock: &_m.Mock}
}

// Status provides a mock function for the type NodeProcess
func (_mock *NodeProcess) Status() status.Status {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 status.Status
	if returnFunc, ok := ret.Get(0).(func() status.Status); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(status.Status)
	}
	return r0
}

// NodeProcess_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type NodeProcess_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *NodeProcess_Expecter) Status() *NodeProcess_Status_Call {
	return &NodeProcess_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *NodeProcess_Status_Call) Run(run func()) *NodeProcess_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NodeProcess_Status_Call) Return(status1 status.Status) *NodeProcess_Status_Call {
	_c.Call.Return(status1)
	return _c
}

func (_c *NodeProcess_Status_Call) RunAndReturn(run func() status.Status) *NodeProcess_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type NodeProcess
func (_mock *NodeProcess) Stop(ctx context.Context) int {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// NodeProcess_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type NodeProcess_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *NodeProcess_Expecter) Stop(ctx interface{}) *NodeProcess_Stop_Call {
	return &NodeProcess_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *NodeProcess_Stop_Call) Run(run func(ctx context.Context)) *NodeProcess_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *NodeProcess_Stop_Call) Return(n int) *NodeProcess_Stop_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *NodeProcess_Stop_Call) RunAndReturn(run func(ctx context.Context) int) *NodeProcess_Stop_Call {
	_c.Call.Return(run)
	return _c
}
