// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/MetalBlockchain/coreth/plugin/evm/client"
	"github.com/MetalBlockchain/metal-network-runner/api"
	"github.com/MetalBlockchain/metalgo/api/admin"
	"github.com/MetalBlockchain/metalgo/api/info"
	"github.com/MetalBlockchain/metalgo/indexer"
	"github.com/MetalBlockchain/metalgo/vms/avm"
	"github.com/MetalBlockchain/metalgo/vms/platformvm"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// AdminAPI provides a mock function for the type Client
func (_mock *Client) AdminAPI() *admin.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AdminAPI")
	}

	var r0 *admin.Client
	if returnFunc, ok := ret.Get(0).(func() *admin.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.Client)
		}
	}
	return r0
}

// Client_AdminAPI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminAPI'
type Client_AdminAPI_Call struct {
	*mock.Call
}

// AdminAPI is a helper method to define mock.On call
func (_e *Client_Expecter) AdminAPI() *Client_AdminAPI_Call {
	return &Client_AdminAPI_Call{Call: _e.mock.On("AdminAPI")}
}

func (_c *Client_AdminAPI_Call) Run(run func()) *Client_AdminAPI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_AdminAPI_Call) Return(client *admin.Client) *Client_AdminAPI_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *Client_AdminAPI_Call) RunAndReturn(run func() *admin.Client) *Client_AdminAPI_Call {
	_c.Call.Return(run)
	return _c
}

// CChainAPI provides a mock function for the type Client
func (_mock *Client) CChainAPI() client.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CChainAPI")
	}

	var r0 client.Client
	if returnFunc, ok := ret.Get(0).(func() client.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}
	return r0
}

// Client_CChainAPI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CChainAPI'
type Client_CChainAPI_Call struct {
	*mock.Call
}

// CChainAPI is a helper method to define mock.On call
func (_e *Client_Expecter) CChainAPI() *Client_CChainAPI_Call {
	return &Client_CChainAPI_Call{Call: _e.mock.On("CChainAPI")}
}

func (_c *Client_CChainAPI_Call) Run(run func()) *Client_CChainAPI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_CChainAPI_Call) Return(client1 client.Client) *Client_CChainAPI_Call {
	_c.Call.Return(client1)
	return _c
}

func (_c *Client_CChainAPI_Call) RunAndReturn(run func() client.Client) *Client_CChainAPI_Call {
	_c.Call.Return(run)
	return _c
}

// CChainEthAPI provides a mock function for the type Client
func (_mock *Client) CChainEthAPI() api.EthClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CChainEthAPI")
	}

	var r0 api.EthClient
	if returnFunc, ok := ret.Get(0).(func() api.EthClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.EthClient)
		}
	}
	return r0
}

// Client_CChainEthAPI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CChainEthAPI'
type Client_CChainEthAPI_Call struct {
	*mock.Call
}

// CChainEthAPI is a helper method to define mock.On call
func (_e *Client_Expecter) CChainEthAPI() *Client_CChainEthAPI_Call {
	return &Client_CChainEthAPI_Call{Call: _e.mock.On("CChainEthAPI")}
}

func (_c *Client_CChainEthAPI_Call) Run(run func()) *Client_CChainEthAPI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_CChainEthAPI_Call) Return(ethClient api.EthClient) *Client_CChainEthAPI_Call {
	_c.Call.Return(ethClient)
	return _c
}

func (_c *Client_CChainEthAPI_Call) RunAndReturn(run func() api.EthClient) *Client_CChainEthAPI_Call {
	_c.Call.Return(run)
	return _c
}

// CChainIndexAPI provides a mock function for the type Client
func (_mock *Client) CChainIndexAPI() *indexer.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CChainIndexAPI")
	}

	var r0 *indexer.Client
	if returnFunc, ok := ret.Get(0).(func() *indexer.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*indexer.Client)
		}
	}
	return r0
}

// Client_CChainIndexAPI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CChainIndexAPI'
type Client_CChainIndexAPI_Call struct {
	*mock.Call
}

// CChainIndexAPI is a helper method to define mock.On call
func (_e *Client_Expecter) CChainIndexAPI() *Client_CChainIndexAPI_Call {
	return &Client_CChainIndexAPI_Call{Call: _e.mock.On("CChainIndexAPI")}
}

func (_c *Client_CChainIndexAPI_Call) Run(run func()) *Client_CChainIndexAPI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_CChainIndexAPI_Call) Return(client1 *indexer.Client) *Client_CChainIndexAPI_Call {
	_c.Call.Return(client1)
	return _c
}

func (_c *Client_CChainIndexAPI_Call) RunAndReturn(run func() *indexer.Client) *Client_CChainIndexAPI_Call {
	_c.Call.Return(run)
	return _c
}

// HealthAPI provides a mock function for the type Client
func (_mock *Client) HealthAPI() api.HealthClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthAPI")
	}

	var r0 api.HealthClient
	if returnFunc, ok := ret.Get(0).(func() api.HealthClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.HealthClient)
		}
	}
	return r0
}

// Client_HealthAPI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthAPI'
type Client_HealthAPI_Call struct {
	*mock.Call
}

// HealthAPI is a helper method to define mock.On call
func (_e *Client_Expecter) HealthAPI() *Client_HealthAPI_Call {
	return &Client_HealthAPI_Call{Call: _e.mock.On("HealthAPI")}
}

func (_c *Client_HealthAPI_Call) Run(run func()) *Client_HealthAPI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_HealthAPI_Call) Return(healthClient api.HealthClient) *Client_HealthAPI_Call {
	_c.Call.Return(healthClient)
	return _c
}

func (_c *Client_HealthAPI_Call) RunAndReturn(run func() api.HealthClient) *Client_HealthAPI_Call {
	_c.Call.Return(run)
	return _c
}

// InfoAPI provides a mock function for the type Client
func (_mock *Client) InfoAPI() *info.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InfoAPI")
	}

	var r0 *info.Client
	if returnFunc, ok := ret.Get(0).(func() *info.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*info.Client)
		}
	}
	return r0
}

// Client_InfoAPI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InfoAPI'
type Client_InfoAPI_Call struct {
	*mock.Call
}

// InfoAPI is a helper method to define mock.On call
func (_e *Client_Expecter) InfoAPI() *Client_InfoAPI_Call {
	return &Client_InfoAPI_Call{Call: _e.mock.On("InfoAPI")}
}

func (_c *Client_InfoAPI_Call) Run(run func()) *Client_InfoAPI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_InfoAPI_Call) Return(client1 *info.Client) *Client_InfoAPI_Call {
	_c.Call.Return(client1)
	return _c
}

func (_c *Client_InfoAPI_Call) RunAndReturn(run func() *info.Client) *Client_InfoAPI_Call {
	_c.Call.Return(run)
	return _c
}

// PChainAPI provides a mock function for the type Client
func (_mock *Client) PChainAPI() *platformvm.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PChainAPI")
	}

	var r0 *platformvm.Client
	if returnFunc, ok := ret.Get(0).(func() *platformvm.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platformvm.Client)
		}
	}
	return r0
}

// Client_PChainAPI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PChainAPI'
type Client_PChainAPI_Call struct {
	*mock.Call
}

// PChainAPI is a helper method to define mock.On call
func (_e *Client_Expecter) PChainAPI() *Client_PChainAPI_Call {
	return &Client_PChainAPI_Call{Call: _e.mock.On("PChainAPI")}
}

func (_c *Client_PChainAPI_Call) Run(run func()) *Client_PChainAPI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_PChainAPI_Call) Return(client1 *platformvm.Client) *Client_PChainAPI_Call {
	_c.Call.Return(client1)
	return _c
}

func (_c *Client_PChainAPI_Call) RunAndReturn(run func() *platformvm.Client) *Client_PChainAPI_Call {
	_c.Call.Return(run)
	return _c
}

// PChainIndexAPI provides a mock function for the type Client
func (_mock *Client) PChainIndexAPI() *indexer.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PChainIndexAPI")
	}

	var r0 *indexer.Client
	if returnFunc, ok := ret.Get(0).(func() *indexer.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*indexer.Client)
		}
	}
	return r0
}

// Client_PChainIndexAPI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PChainIndexAPI'
type Client_PChainIndexAPI_Call struct {
	*mock.Call
}

// PChainIndexAPI is a helper method to define mock.On call
func (_e *Client_Expecter) PChainIndexAPI() *Client_PChainIndexAPI_Call {
	return &Client_PChainIndexAPI_Call{Call: _e.mock.On("PChainIndexAPI")}
}

func (_c *Client_PChainIndexAPI_Call) Run(run func()) *Client_PChainIndexAPI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_PChainIndexAPI_Call) Return(client1 *indexer.Client) *Client_PChainIndexAPI_Call {
	_c.Call.Return(client1)
	return _c
}

func (_c *Client_PChainIndexAPI_Call) RunAndReturn(run func() *indexer.Client) *Client_PChainIndexAPI_Call {
	_c.Call.Return(run)
	return _c
}

// XChainAPI provides a mock function for the type Client
func (_mock *Client) XChainAPI() *avm.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for XChainAPI")
	}

	var r0 *avm.Client
	if returnFunc, ok := ret.Get(0).(func() *avm.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*avm.Client)
		}
	}
	return r0
}

// Client_XChainAPI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'XChainAPI'
type Client_XChainAPI_Call struct {
	*mock.Call
}

// XChainAPI is a helper method to define mock.On call
func (_e *Client_Expecter) XChainAPI() *Client_XChainAPI_Call {
	return &Client_XChainAPI_Call{Call: _e.mock.On("XChainAPI")}
}

func (_c *Client_XChainAPI_Call) Run(run func()) *Client_XChainAPI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_XChainAPI_Call) Return(client1 *avm.Client) *Client_XChainAPI_Call {
	_c.Call.Return(client1)
	return _c
}

func (_c *Client_XChainAPI_Call) RunAndReturn(run func() *avm.Client) *Client_XChainAPI_Call {
	_c.Call.Return(run)
	return _c
}

// XChainWalletAPI provides a mock function for the type Client
func (_mock *Client) XChainWalletAPI() *avm.WalletClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for XChainWalletAPI")
	}

	var r0 *avm.WalletClient
	if returnFunc, ok := ret.Get(0).(func() *avm.WalletClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*avm.WalletClient)
		}
	}
	return r0
}

// Client_XChainWalletAPI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'XChainWalletAPI'
type Client_XChainWalletAPI_Call struct {
	*mock.Call
}

// XChainWalletAPI is a helper method to define mock.On call
func (_e *Client_Expecter) XChainWalletAPI() *Client_XChainWalletAPI_Call {
	return &Client_XChainWalletAPI_Call{Call: _e.mock.On("XChainWalletAPI")}
}

func (_c *Client_XChainWalletAPI_Call) Run(run func()) *Client_XChainWalletAPI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_XChainWalletAPI_Call) Return(walletClient *avm.WalletClient) *Client_XChainWalletAPI_Call {
	_c.Call.Return(walletClient)
	return _c
}

func (_c *Client_XChainWalletAPI_Call) RunAndReturn(run func() *avm.WalletClient) *Client_XChainWalletAPI_Call {
	_c.Call.Return(run)
	return _c
}
