// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"math/big"

	"github.com/MetalBlockchain/coreth/interfaces"
	"github.com/MetalBlockchain/libevm"
	"github.com/MetalBlockchain/libevm/common"
	"github.com/MetalBlockchain/libevm/core/types"
	mock "github.com/stretchr/testify/mock"
)

// NewEthClient creates a new instance of EthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *EthClient {
	mock := &EthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EthClient is an autogenerated mock type for the EthClient type
type EthClient struct {
	mock.Mock
}

type EthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *EthClient) EXPECT() *EthClient_Expecter {
	return &EthClient_Expecter{mock: &_m.Mock}
}

// AcceptedCallContract provides a mock function for the type EthClient
func (_mock *EthClient) AcceptedCallContract(context1 context.Context, callMsg ethereum.CallMsg) ([]byte, error) {
	ret := _mock.Called(context1, callMsg)

	if len(ret) == 0 {
		panic("no return value specified for AcceptedCallContract")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.CallMsg) ([]byte, error)); ok {
		return returnFunc(context1, callMsg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.CallMsg) []byte); ok {
		r0 = returnFunc(context1, callMsg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ethereum.CallMsg) error); ok {
		r1 = returnFunc(context1, callMsg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EthClient_AcceptedCallContract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptedCallContract'
type EthClient_AcceptedCallContract_Call struct {
	*mock.Call
}

// AcceptedCallContract is a helper method to define mock.On call
//   - context1 context.Context
//   - callMsg ethereum.CallMsg
func (_e *EthClient_Expecter) AcceptedCallContract(context1 interface{}, callMsg interface{}) *EthClient_AcceptedCallContract_Call {
	return &EthClient_AcceptedCallContract_Call{Call: _e.mock.On("AcceptedCallContract", context1, callMsg)}
}

func (_c *EthClient_AcceptedCallContract_Call) Run(run func(context1 context.Context, callMsg ethereum.CallMsg)) *EthClient_AcceptedCallContract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ethereum.CallMsg
		if args[1] != nil {
			arg1 = args[1].(ethereum.CallMsg)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EthClient_AcceptedCallContract_Call) Return(bytes []byte, err error) *EthClient_AcceptedCallContract_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *EthClient_AcceptedCallContract_Call) RunAndReturn(run func(context1 context.Context, callMsg ethereum.CallMsg) ([]byte, error)) *EthClient_AcceptedCallContract_Call {
	_c.Call.Return(run)
	return _c
}

// AcceptedCodeAt provides a mock function for the type EthClient
func (_mock *EthClient) AcceptedCodeAt(context1 context.Context, address common.Address) ([]byte, error) {
	ret := _mock.Called(context1, address)

	if len(ret) == 0 {
		panic("no return value specified for AcceptedCodeAt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Address) ([]byte, error)); ok {
		return returnFunc(context1, address)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Address) []byte); ok {
		r0 = returnFunc(context1, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, common.Address) error); ok {
		r1 = returnFunc(context1, address)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EthClient_AcceptedCodeAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptedCodeAt'
type EthClient_AcceptedCodeAt_Call struct {
	*mock.Call
}

// AcceptedCodeAt is a helper method to define mock.On call
//   - context1 context.Context
//   - address common.Address
func (_e *EthClient_Expecter) AcceptedCodeAt(context1 interface{}, address interface{}) *EthClient_AcceptedCodeAt_Call {
	return &EthClient_AcceptedCodeAt_Call{Call: _e.mock.On("AcceptedCodeAt", context1, address)}
}

func (_c *EthClient_AcceptedCodeAt_Call) Run(run func(context1 context.Context, address common.Address)) *EthClient_AcceptedCodeAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Address
		if args[1] != nil {
			arg1 = args[1].(common.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EthClient_AcceptedCodeAt_Call) Return(bytes []byte, err error) *EthClient_AcceptedCodeAt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *EthClient_AcceptedCodeAt_Call) RunAndReturn(run func(context1 context.Context, address common.Address) ([]byte, error)) *EthClient_AcceptedCodeAt_Call {
	_c.Call.Return(run)
	return _c
}

// AcceptedNonceAt provides a mock function for the type EthClient
func (_mock *EthClient) AcceptedNonceAt(context1 context.Context, address common.Address) (uint64, error) {
	ret := _mock.Called(context1, address)

	if len(ret) == 0 {
		panic("no return value specified for AcceptedNonceAt")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Address) (uint64, error)); ok {
		return returnFunc(context1, address)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Address) uint64); ok {
		r0 = returnFunc(context1, address)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, common.Address) error); ok {
		r1 = returnFunc(context1, address)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EthClient_AcceptedNonceAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptedNonceAt'
type EthClient_AcceptedNonceAt_Call struct {
	*mock.Call
}

// AcceptedNonceAt is a helper method to define mock.On call
//   - context1 context.Context
//   - address common.Address
func (_e *EthClient_Expecter) AcceptedNonceAt(context1 interface{}, address interface{}) *EthClient_AcceptedNonceAt_Call {
	return &EthClient_AcceptedNonceAt_Call{Call: _e.mock.On("AcceptedNonceAt", context1, address)}
}

func (_c *EthClient_AcceptedNonceAt_Call) Run(run func(context1 context.Context, address common.Address)) *EthClient_AcceptedNonceAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Address
		if args[1] != nil {
			arg1 = args[1].(common.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EthClient_AcceptedNonceAt_Call) Return(v uint64, err error) *EthClient_AcceptedNonceAt_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *EthClient_AcceptedNonceAt_Call) RunAndReturn(run func(context1 context.Context, address common.Address) (uint64, error)) *EthClient_AcceptedNonceAt_Call {
	_c.Call.Return(run)
	return _c
}

// BalanceAt provides a mock function for the type EthClient
func (_mock *EthClient) BalanceAt(context1 context.Context, address common.Address, intParam *big.Int) (*big.Int, error) {
	ret := _mock.Called(context1, address, intParam)

	if len(ret) == 0 {
		panic("no return value specified for BalanceAt")
	}

	var r0 *big.Int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int) (*big.Int, error)); ok {
		return returnFunc(context1, address, intParam)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int) *big.Int); ok {
		r0 = returnFunc(context1, address, intParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, common.Address, *big.Int) error); ok {
		r1 = returnFunc(context1, address, intParam)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EthClient_BalanceAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BalanceAt'
type EthClient_BalanceAt_Call struct {
	*mock.Call
}

// BalanceAt is a helper method to define mock.On call
//   - context1 context.Context
//   - address common.Address
//   - intParam *big.Int
func (_e *EthClient_Expecter) BalanceAt(context1 interface{}, address interface{}, intParam interface{}) *EthClient_BalanceAt_Call {
	return &EthClient_BalanceAt_Call{Call: _e.mock.On("BalanceAt", context1, address, intParam)}
}

func (_c *EthClient_BalanceAt_Call) Run(run func(context1 context.Context, address common.Address, intParam *big.Int)) *EthClient_BalanceAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Address
		if args[1] != nil {
			arg1 = args[1].(common.Address)
		}
		var arg2 *big.Int
		if args[2] != nil {
			arg2 = args[2].(*big.Int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EthClient_BalanceAt_Call) Return(intParam1 *big.Int, err error) *EthClient_BalanceAt_Call {
	_c.Call.Return(intParam1, err)
	return _c
}

func (_c *EthClient_BalanceAt_Call) RunAndReturn(run func(context1 context.Context, address common.Address, intParam *big.Int) (*big.Int, error)) *EthClient_BalanceAt_Call {
	_c.Call.Return(run)
	return _c
}

// BlockByHash provides a mock function for the type EthClient
func (_mock *EthClient) BlockByHash(context1 context.Context, hash common.Hash) (*types.Block, error) {
	ret := _mock.Called(context1, hash)

	if len(ret) == 0 {
		panic("no return value specified for BlockByHash")
	}

	var r0 *types.Block
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Hash) (*types.Block, error)); ok {
		return returnFunc(context1, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Hash) *types.Block); ok {
		r0 = returnFunc(context1, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Block)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, common.Hash) error); ok {
		r1 = returnFunc(context1, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EthClient_BlockByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockByHash'
type EthClient_BlockByHash_Call struct {
	*mock.Call
}

// BlockByHash is a helper method to define mock.On call
//   - context1 context.Context
//   - hash common.Hash
func (_e *EthClient_Expecter) BlockByHash(context1 interface{}, hash interface{}) *EthClient_BlockByHash_Call {
	return &EthClient_BlockByHash_Call{Call: _e.mock.On("BlockByHash", context1, hash)}
}

func (_c *EthClient_BlockByHash_Call) Run(run func(context1 context.Context, hash common.Hash)) *EthClient_BlockByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Hash
		if args[1] != nil {
			arg1 = args[1].(common.Hash)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EthClient_BlockByHash_Call) Return(block *types.Block, err error) *EthClient_BlockByHash_Call {
	_c.Call.Return(block, err)
	return _c
}

func (_c *EthClient_BlockByHash_Call) RunAndReturn(run func(context1 context.Context, hash common.Hash) (*types.Block, error)) *EthClient_BlockByHash_Call {
	_c.Call.Return(run)
	return _c
}

// BlockByNumber provides a mock function for the type EthClient
func (_mock *EthClient) BlockByNumber(context1 context.Context, intParam *big.Int) (*types.Block, error) {
	ret := _mock.Called(context1, intParam)

	if len(ret) == 0 {
		panic("no return value specified for BlockByNumber")
	}

	var r0 *types.Block
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *big.Int) (*types.Block, error)); ok {
		return returnFunc(context1, intParam)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *big.Int) *types.Block); ok {
		r0 = returnFunc(context1, intParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Block)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *big.Int) error); ok {
		r1 = returnFunc(context1, intParam)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EthClient_BlockByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockByNumber'
type EthClient_BlockByNumber_Call struct {
	*mock.Call
}

// BlockByNumber is a helper method to define mock.On call
//   - context1 context.Context
//   - intParam *big.Int
func (_e *EthClient_Expecter) BlockByNumber(context1 interface{}, intParam interface{}) *EthClient_BlockByNumber_Call {
	return &EthClient_BlockByNumber_Call{Call: _e.mock.On("BlockByNumber", context1, intParam)}
}

func (_c *EthClient_BlockByNumber_Call) Run(run func(context1 context.Context, intParam *big.Int)) *EthClient_BlockByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *big.Int
		if args[1] != nil {
			arg1 = args[1].(*big.Int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EthClient_BlockByNumber_Call) Return(block *types.Block, err error) *EthClient_BlockByNumber_Call {
	_c.Call.Return(block, err)
	return _c
}

func (_c *EthClient_BlockByNumber_Call) RunAndReturn(run func(context1 context.Context, intParam *big.Int) (*types.Block, error)) *EthClient_BlockByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// BlockNumber provides a mock function for the type EthClient
func (_mock *EthClient) BlockNumber(context1 context.Context) (uint64, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for BlockNumber")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (uint64, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EthClient_BlockNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockNumber'
type EthClient_BlockNumber_Call struct {
	*mock.Call
}

// BlockNumber is a helper method to define mock.On call
//   - context1 context.Context
func (_e *EthClient_Expecter) BlockNumber(context1 interface{}) *EthClient_BlockNumber_Call {
	return &EthClient_BlockNumber_Call{Call: _e.mock.On("BlockNumber", context1)}
}

func (_c *EthClient_BlockNumber_Call) Run(run func(context1 context.Context)) *EthClient_BlockNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EthClient_BlockNumber_Call) Return(v uint64, err error) *EthClient_BlockNumber_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *EthClient_BlockNumber_Call) RunAndReturn(run func(context1 context.Context) (uint64, error)) *EthClient_BlockNumber_Call {
	_c.Call.Return(run)
	return _c
}

// CallContract provides a mock function for the type EthClient
func (_mock *EthClient) CallContract(context1 context.Context, callMsg ethereum.CallMsg, intParam *big.Int) ([]byte, error) {
	ret := _mock.Called(context1, callMsg, intParam)

	if len(ret) == 0 {
		panic("no return value specified for CallContract")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.CallMsg, *big.Int) ([]byte, error)); ok {
		return returnFunc(context1, callMsg, intParam)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.CallMsg, *big.Int) []byte); ok {
		r0 = returnFunc(context1, callMsg, intParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ethereum.CallMsg, *big.Int) error); ok {
		r1 = returnFunc(context1, callMsg, intParam)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EthClient_CallContract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallContract'
type EthClient_CallContract_Call struct {
	*mock.Call
}

// CallContract is a helper method to define mock.On call
//   - context1 context.Context
//   - callMsg ethereum.CallMsg
//   - intParam *big.Int
func (_e *EthClient_Expecter) CallContract(context1 interface{}, callMsg interface{}, intParam interface{}) *EthClient_CallContract_Call {
	return &EthClient_CallContract_Call{Call: _e.mock.On("CallContract", context1, callMsg, intParam)}
}

func (_c *EthClient_CallContract_Call) Run(run func(context1 context.Context, callMsg ethereum.CallMsg, intParam *big.Int)) *EthClient_CallContract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ethereum.CallMsg
		if args[1] != nil {
			arg1 = args[1].(ethereum.CallMsg)
		}
		var arg2 *big.Int
		if args[2] != nil {
			arg2 = args[2].(*big.Int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EthClient_CallContract_Call) Return(bytes []byte, err error) *EthClient_CallContract_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *EthClient_CallContract_Call) RunAndReturn(run func(context1 context.Context, callMsg ethereum.CallMsg, intParam *big.Int) ([]byte, error)) *EthClient_CallContract_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type EthClient
func (_mock *EthClient) Close() {
	_mock.Called()
	return
}

// EthClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type EthClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *EthClient_Expecter) Close() *EthClient_Close_Call {
	return &EthClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *EthClient_Close_Call) Run(run func()) *EthClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EthClient_Close_Call) Return() *EthClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *EthClient_Close_Call) RunAndReturn(run func()) *EthClient_Close_Call {
	_c.Run(run)
	return _c
}

// CodeAt provides a mock function for the type EthClient
func (_mock *EthClient) CodeAt(context1 context.Context, address common.Address, intParam *big.Int) ([]byte, error) {
	ret := _mock.Called(context1, address, intParam)

	if len(ret) == 0 {
		panic("no return value specified for CodeAt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int) ([]byte, error)); ok {
		return returnFunc(context1, address, intParam)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int) []byte); ok {
		r0 = returnFunc(context1, address, intParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, common.Address, *big.Int) error); ok {
		r1 = returnFunc(context1, address, intParam)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EthClient_CodeAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CodeAt'
type EthClient_CodeAt_Call struct {
	*mock.Call
}

// CodeAt is a helper method to define mock.On call
//   - context1 context.Context
//   - address common.Address
//   - intParam *big.Int
func (_e *EthClient_Expecter) CodeAt(context1 interface{}, address interface{}, intParam interface{}) *EthClient_CodeAt_Call {
	return &EthClient_CodeAt_Call{Call: _e.mock.On("CodeAt", context1, address, intParam)}
}

func (_c *EthClient_CodeAt_Call) Run(run func(context1 context.Context, address common.Address, intParam *big.Int)) *EthClient_CodeAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Address
		if args[1] != nil {
			arg1 = args[1].(common.Address)
		}
		var arg2 *big.Int
		if args[2] != nil {
			arg2 = args[2].(*big.Int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EthClient_CodeAt_Call) Return(bytes []byte, err error) *EthClient_CodeAt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *EthClient_CodeAt_Call) RunAndReturn(run func(context1 context.Context, address common.Address, intParam *big.Int) ([]byte, error)) *EthClient_CodeAt_Call {
	_c.Call.Return(run)
	return _c
}

// EstimateGas provides a mock function for the type EthClient
func (_mock *EthClient) EstimateGas(context1 context.Context, callMsg ethereum.CallMsg) (uint64, error) {
	ret := _mock.Called(context1, callMsg)

	if len(ret) == 0 {
		panic("no return value specified for EstimateGas")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.CallMsg) (uint64, error)); ok {
		return returnFunc(context1, callMsg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.CallMsg) uint64); ok {
		r0 = returnFunc(context1, callMsg)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ethereum.CallMsg) error); ok {
		r1 = returnFunc(context1, callMsg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EthClient_EstimateGas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EstimateGas'
type EthClient_EstimateGas_Call struct {
	*mock.Call
}

// EstimateGas is a helper method to define mock.On call
//   - context1 context.Context
//   - callMsg ethereum.CallMsg
func (_e *EthClient_Expecter) EstimateGas(context1 interface{}, callMsg interface{}) *EthClient_EstimateGas_Call {
	return &EthClient_EstimateGas_Call{Call: _e.mock.On("EstimateGas", context1, callMsg)}
}

func (_c *EthClient_EstimateGas_Call) Run(run func(context1 context.Context, callMsg ethereum.CallMsg)) *EthClient_EstimateGas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ethereum.CallMsg
		if args[1] != nil {
			arg1 = args[1].(ethereum.CallMsg)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EthClient_EstimateGas_Call) Return(v uint64, err error) *EthClient_EstimateGas_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *EthClient_EstimateGas_Call) RunAndReturn(run func(context1 context.Context, callMsg ethereum.CallMsg) (uint64, error)) *EthClient_EstimateGas_Call {
	_c.Call.Return(run)
	return _c
}

// FilterLogs provides a mock function for the type EthClient
func (_mock *EthClient) FilterLogs(context1 context.Context, filterQuery ethereum.FilterQuery) ([]types.Log, error) {
	ret := _mock.Called(context1, filterQuery)

	if len(ret) == 0 {
		panic("no return value specified for FilterLogs")
	}

	var r0 []types.Log
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.FilterQuery) ([]types.Log, error)); ok {
		return returnFunc(context1, filterQuery)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.FilterQuery) []types.Log); ok {
		r0 = returnFunc(context1, filterQuery)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Log)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ethereum.FilterQuery) error); ok {
		r1 = returnFunc(context1, filterQuery)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EthClient_FilterLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterLogs'
type EthClient_FilterLogs_Call struct {
	*mock.Call
}

// FilterLogs is a helper method to define mock.On call
//   - context1 context.Context
//   - filterQuery ethereum.FilterQuery
func (_e *EthClient_Expecter) FilterLogs(context1 interface{}, filterQuery interface{}) *EthClient_FilterLogs_Call {
	return &EthClient_FilterLogs_Call{Call: _e.mock.On("FilterLogs", context1, filterQuery)}
}

func (_c *EthClient_FilterLogs_Call) Run(run func(context1 context.Context, filterQuery ethereum.FilterQuery)) *EthClient_FilterLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ethereum.FilterQuery
		if args[1] != nil {
			arg1 = args[1].(ethereum.FilterQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EthClient_FilterLogs_Call) Return(logs []types.Log, err error) *EthClient_FilterLogs_Call {
	_c.Call.Return(logs, err)
	return _c
}

func (_c *EthClient_FilterLogs_Call) RunAndReturn(run func(context1 context.Context, filterQuery ethereum.FilterQuery) ([]types.Log, error)) *EthClient_FilterLogs_Call {
	_c.Call.Return(run)
	return _c
}

// HeaderByNumber provides a mock function for the type EthClient
func (_mock *EthClient) HeaderByNumber(context1 context.Context, intParam *big.Int) (*types.Header, error) {
	ret := _mock.Called(context1, intParam)

	if len(ret) == 0 {
		panic("no return value specified for HeaderByNumber")
	}

	var r0 *types.Header
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *big.Int) (*types.Header, error)); ok {
		return returnFunc(context1, intParam)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *big.Int) *types.Header); ok {
		r0 = returnFunc(context1, intParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Header)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *big.Int) error); ok {
		r1 = returnFunc(context1, intParam)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EthClient_HeaderByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeaderByNumber'
type EthClient_HeaderByNumber_Call struct {
	*mock.Call
}

// HeaderByNumber is a helper method to define mock.On call
//   - context1 context.Context
//   - intParam *big.Int
func (_e *EthClient_Expecter) HeaderByNumber(context1 interface{}, intParam interface{}) *EthClient_HeaderByNumber_Call {
	return &EthClient_HeaderByNumber_Call{Call: _e.mock.On("HeaderByNumber", context1, intParam)}
}

func (_c *EthClient_HeaderByNumber_Call) Run(run func(context1 context.Context, intParam *big.Int)) *EthClient_HeaderByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *big.Int
		if args[1] != nil {
			arg1 = args[1].(*big.Int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EthClient_HeaderByNumber_Call) Return(header *types.Header, err error) *EthClient_HeaderByNumber_Call {
	_c.Call.Return(header, err)
	return _c
}

func (_c *EthClient_HeaderByNumber_Call) RunAndReturn(run func(context1 context.Context, intParam *big.Int) (*types.Header, error)) *EthClient_HeaderByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// NonceAt provides a mock function for the type EthClient
func (_mock *EthClient) NonceAt(context1 context.Context, address common.Address, intParam *big.Int) (uint64, error) {
	ret := _mock.Called(context1, address, intParam)

	if len(ret) == 0 {
		panic("no return value specified for NonceAt")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int) (uint64, error)); ok {
		return returnFunc(context1, address, intParam)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int) uint64); ok {
		r0 = returnFunc(context1, address, intParam)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, common.Address, *big.Int) error); ok {
		r1 = returnFunc(context1, address, intParam)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EthClient_NonceAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NonceAt'
type EthClient_NonceAt_Call struct {
	*mock.Call
}

// NonceAt is a helper method to define mock.On call
//   - context1 context.Context
//   - address common.Address
//   - intParam *big.Int
func (_e *EthClient_Expecter) NonceAt(context1 interface{}, address interface{}, intParam interface{}) *EthClient_NonceAt_Call {
	return &EthClient_NonceAt_Call{Call: _e.mock.On("NonceAt", context1, address, intParam)}
}

func (_c *EthClient_NonceAt_Call) Run(run func(context1 context.Context, address common.Address, intParam *big.Int)) *EthClient_NonceAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Address
		if args[1] != nil {
			arg1 = args[1].(common.Address)
		}
		var arg2 *big.Int
		if args[2] != nil {
			arg2 = args[2].(*big.Int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EthClient_NonceAt_Call) Return(v uint64, err error) *EthClient_NonceAt_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *EthClient_NonceAt_Call) RunAndReturn(run func(context1 context.Context, address common.Address, intParam *big.Int) (uint64, error)) *EthClient_NonceAt_Call {
	_c.Call.Return(run)
	return _c
}

// SendTransaction provides a mock function for the type EthClient
func (_mock *EthClient) SendTransaction(context1 context.Context, transaction *types.Transaction) error {
	ret := _mock.Called(context1, transaction)

	if len(ret) == 0 {
		panic("no return value specified for SendTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Transaction) error); ok {
		r0 = returnFunc(context1, transaction)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EthClient_SendTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTransaction'
type EthClient_SendTransaction_Call struct {
	*mock.Call
}

// SendTransaction is a helper method to define mock.On call
//   - context1 context.Context
//   - transaction *types.Transaction
func (_e *EthClient_Expecter) SendTransaction(context1 interface{}, transaction interface{}) *EthClient_SendTransaction_Call {
	return &EthClient_SendTransaction_Call{Call: _e.mock.On("SendTransaction", context1, transaction)}
}

func (_c *EthClient_SendTransaction_Call) Run(run func(context1 context.Context, transaction *types.Transaction)) *EthClient_SendTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Transaction
		if args[1] != nil {
			arg1 = args[1].(*types.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EthClient_SendTransaction_Call) Return(err error) *EthClient_SendTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EthClient_SendTransaction_Call) RunAndReturn(run func(context1 context.Context, transaction *types.Transaction) error) *EthClient_SendTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeFilterLogs provides a mock function for the type EthClient
func (_mock *EthClient) SubscribeFilterLogs(context1 context.Context, filterQuery ethereum.FilterQuery, logCh chan<- types.Log) (interfaces.Subscription, error) {
	ret := _mock.Called(context1, filterQuery, logCh)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeFilterLogs")
	}

	var r0 interfaces.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.FilterQuery, chan<- types.Log) (interfaces.Subscription, error)); ok {
		return returnFunc(context1, filterQuery, logCh)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.FilterQuery, chan<- types.Log) interfaces.Subscription); ok {
		r0 = returnFunc(context1, filterQuery, logCh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ethereum.FilterQuery, chan<- types.Log) error); ok {
		r1 = returnFunc(context1, filterQuery, logCh)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EthClient_SubscribeFilterLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeFilterLogs'
type EthClient_SubscribeFilterLogs_Call struct {
	*mock.Call
}

// SubscribeFilterLogs is a helper method to define mock.On call
//   - context1 context.Context
//   - filterQuery ethereum.FilterQuery
//   - logCh chan<- types.Log
func (_e *EthClient_Expecter) SubscribeFilterLogs(context1 interface{}, filterQuery interface{}, logCh interface{}) *EthClient_SubscribeFilterLogs_Call {
	return &EthClient_SubscribeFilterLogs_Call{Call: _e.mock.On("SubscribeFilterLogs", context1, filterQuery, logCh)}
}

func (_c *EthClient_SubscribeFilterLogs_Call) Run(run func(context1 context.Context, filterQuery ethereum.FilterQuery, logCh chan<- types.Log)) *EthClient_SubscribeFilterLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ethereum.FilterQuery
		if args[1] != nil {
			arg1 = args[1].(ethereum.FilterQuery)
		}
		var arg2 chan<- types.Log
		if args[2] != nil {
			arg2 = args[2].(chan<- types.Log)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EthClient_SubscribeFilterLogs_Call) Return(subscription interfaces.Subscription, err error) *EthClient_SubscribeFilterLogs_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *EthClient_SubscribeFilterLogs_Call) RunAndReturn(run func(context1 context.Context, filterQuery ethereum.FilterQuery, logCh chan<- types.Log) (interfaces.Subscription, error)) *EthClient_SubscribeFilterLogs_Call {
	_c.Call.Return(run)
	return _c
}

// SuggestGasPrice provides a mock function for the type EthClient
func (_mock *EthClient) SuggestGasPrice(context1 context.Context) (*big.Int, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for SuggestGasPrice")
	}

	var r0 *big.Int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*big.Int, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *big.Int); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EthClient_SuggestGasPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuggestGasPrice'
type EthClient_SuggestGasPrice_Call struct {
	*mock.Call
}

// SuggestGasPrice is a helper method to define mock.On call
//   - context1 context.Context
func (_e *EthClient_Expecter) SuggestGasPrice(context1 interface{}) *EthClient_SuggestGasPrice_Call {
	return &EthClient_SuggestGasPrice_Call{Call: _e.mock.On("SuggestGasPrice", context1)}
}

func (_c *EthClient_SuggestGasPrice_Call) Run(run func(context1 context.Context)) *EthClient_SuggestGasPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EthClient_SuggestGasPrice_Call) Return(intParam *big.Int, err error) *EthClient_SuggestGasPrice_Call {
	_c.Call.Return(intParam, err)
	return _c
}

func (_c *EthClient_SuggestGasPrice_Call) RunAndReturn(run func(context1 context.Context) (*big.Int, error)) *EthClient_SuggestGasPrice_Call {
	_c.Call.Return(run)
	return _c
}

// SuggestGasTipCap provides a mock function for the type EthClient
func (_mock *EthClient) SuggestGasTipCap(context1 context.Context) (*big.Int, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for SuggestGasTipCap")
	}

	var r0 *big.Int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*big.Int, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *big.Int); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EthClient_SuggestGasTipCap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuggestGasTipCap'
type EthClient_SuggestGasTipCap_Call struct {
	*mock.Call
}

// SuggestGasTipCap is a helper method to define mock.On call
//   - context1 context.Context
func (_e *EthClient_Expecter) SuggestGasTipCap(context1 interface{}) *EthClient_SuggestGasTipCap_Call {
	return &EthClient_SuggestGasTipCap_Call{Call: _e.mock.On("SuggestGasTipCap", context1)}
}

func (_c *EthClient_SuggestGasTipCap_Call) Run(run func(context1 context.Context)) *EthClient_SuggestGasTipCap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EthClient_SuggestGasTipCap_Call) Return(intParam *big.Int, err error) *EthClient_SuggestGasTipCap_Call {
	_c.Call.Return(intParam, err)
	return _c
}

func (_c *EthClient_SuggestGasTipCap_Call) RunAndReturn(run func(context1 context.Context) (*big.Int, error)) *EthClient_SuggestGasTipCap_Call {
	_c.Call.Return(run)
	return _c
}

// TransactionReceipt provides a mock function for the type EthClient
func (_mock *EthClient) TransactionReceipt(context1 context.Context, hash common.Hash) (*types.Receipt, error) {
	ret := _mock.Called(context1, hash)

	if len(ret) == 0 {
		panic("no return value specified for TransactionReceipt")
	}

	var r0 *types.Receipt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Hash) (*types.Receipt, error)); ok {
		return returnFunc(context1, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Hash) *types.Receipt); ok {
		r0 = returnFunc(context1, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Receipt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, common.Hash) error); ok {
		r1 = returnFunc(context1, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EthClient_TransactionReceipt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransactionReceipt'
type EthClient_TransactionReceipt_Call struct {
	*mock.Call
}

// TransactionReceipt is a helper method to define mock.On call
//   - context1 context.Context
//   - hash common.Hash
func (_e *EthClient_Expecter) TransactionReceipt(context1 interface{}, hash interface{}) *EthClient_TransactionReceipt_Call {
	return &EthClient_TransactionReceipt_Call{Call: _e.mock.On("TransactionReceipt", context1, hash)}
}

func (_c *EthClient_TransactionReceipt_Call) Run(run func(context1 context.Context, hash common.Hash)) *EthClient_TransactionReceipt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Hash
		if args[1] != nil {
			arg1 = args[1].(common.Hash)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EthClient_TransactionReceipt_Call) Return(receipt *types.Receipt, err error) *EthClient_TransactionReceipt_Call {
	_c.Call.Return(receipt, err)
	return _c
}

func (_c *EthClient_TransactionReceipt_Call) RunAndReturn(run func(context1 context.Context, hash common.Hash) (*types.Receipt, error)) *EthClient_TransactionReceipt_Call {
	_c.Call.Return(run)
	return _c
}
